[build]
  publish = "."
  command = """
    cd $PUBLISH_DIR
    sed -i "s|VITE_FIREBASE_API_KEY_PLACEHOLDER|$FIREBASE_API_KEY|g" index.html
    sed -i "s|VITE_FIREBASE_AUTH_DOMAIN_PLACEHOLDER|$FIREBASE_AUTH_DOMAIN|g" index.html
    sed -i "s|VITE_FIREBASE_DATABASE_URL_PLACEHOLDER|$FIREBASE_DATABASE_URL|g" index.html
    sed -i "s|VITE_FIREBASE_PROJECT_ID_PLACEHOLDER|$FIREBASE_PROJECT_ID|g" index.html
    sed -i "s|VITE_FIREBASE_STORAGE_BUCKET_PLACEHOLDER|$FIREBASE_STORAGE_BUCKET|g" index.html
    sed -i "s|VITE_FIREBASE_MESSAGING_SENDER_ID_PLACEHOLDER|$FIREBASE_MESSAGING_SENDER_ID|g" index.html
    sed -i "s|VITE_FIREBASE_APP_ID_PLACEHOLDER|$FIREBASE_APP_ID|g" index.html
    sed -i "s|VITE_FIREBASE_MEASUREMENT_ID_PLACEHOLDER|$FIREBASE_MEASUREMENT_ID|g" index.html
  """

[build.environment]
  FIREBASE_API_KEY = "${VITE_FIREBASE_API_KEY}"
  FIREBASE_AUTH_DOMAIN = "${VITE_FIREBASE_AUTH_DOMAIN}"
  FIREBASE_DATABASE_URL = "${VITE_FIREBASE_DATABASE_URL}"
  FIREBASE_PROJECT_ID = "${VITE_FIREBASE_PROJECT_ID}"
  FIREBASE_STORAGE_BUCKET = "${VITE_FIREBASE_STORAGE_BUCKET}"
  FIREBASE_MESSAGING_SENDER_ID = "${VITE_FIREBASE_MESSAGING_SENDER_ID}"
  FIREBASE_APP_ID = "${VITE_FIREBASE_APP_ID}"
  FIREBASE_MEASUREMENT_ID = "${VITE_FIREBASE_MEASUREMENT_ID}"
